Repository ovh-ux/ng-ovh-utils, pull requests merged in 2019-08, with the labels that each got.

#44 refactor(wizard): remove unused redirectFocus function
  src/wizard/wizardStep/wizardStep-directive.js
  src/wizard/wizardStep/wizardStep.html
Labels: enhancement

#46 fix: avoid crash if no api options are passed
  src/poll/poll-service.js
Labels: bug

#48 Release v14.0.4
  package.json
  src/alerter/alerter-service.js
  src/wizard/wizardStep/wizardStep-directive.js
  src/wizard/wizardStep/wizardStep.html
  yarn.lock
Labels: release
